-- Update embedding column from VECTOR(384) to VECTOR(640) for HybridEncoder support.
-- HybridEncoder concatenates semantic (384 dims) + structured (256 dims) = 640 dims.
-- All existing embeddings are invalidated and will be re-generated by the embedding worker.

DROP INDEX IF EXISTS idx_atoms_embedding;

ALTER TABLE atoms DROP COLUMN IF EXISTS embedding;
ALTER TABLE atoms ADD COLUMN embedding VECTOR(640) NULL;

UPDATE atoms SET embedding_status = 'pending';

CREATE INDEX idx_atoms_embedding ON atoms USING HNSW (embedding vector_cosine_ops) WHERE embedding IS NOT NULL;
